# Generated by Django 3.1 on 2020-08-07 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='is_favorite',
            field=models.BooleanField(default='False'),
        ),
    ]
